language: php

php:
  - 5.3
  - 5.4
  - 5.5
  
script:
    - phpunit --coverage-clover=coverage.clover -c app
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
